// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace EotRGameplayTags
{
	ECHOESOFTHEROZLOM_API	FGameplayTag FindTagByString(const FString& TagString, bool bMatchPartialString = false);

	// Declare all of the custom native tags that EotR will use
	ECHOESOFTHEROZLOM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_IsDead);
	ECHOESOFTHEROZLOM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cooldown);
	ECHOESOFTHEROZLOM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cost);
	ECHOESOFTHEROZLOM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_TagsBlocked);
	ECHOESOFTHEROZLOM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_TagsMissing);
	ECHOESOFTHEROZLOM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Networking);
	ECHOESOFTHEROZLOM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_ActivationGroup);

	ECHOESOFTHEROZLOM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Behavior_SurvivesDeath);

	ECHOESOFTHEROZLOM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	ECHOESOFTHEROZLOM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Mouse);
	ECHOESOFTHEROZLOM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Stick);
	ECHOESOFTHEROZLOM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	ECHOESOFTHEROZLOM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_AutoRun);

	ECHOESOFTHEROZLOM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_Spawned);
	ECHOESOFTHEROZLOM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataAvailable);
	ECHOESOFTHEROZLOM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataInitialized);
	ECHOESOFTHEROZLOM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_GameplayReady);

	ECHOESOFTHEROZLOM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Death);
	ECHOESOFTHEROZLOM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Reset);
	ECHOESOFTHEROZLOM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_RequestReset);

	ECHOESOFTHEROZLOM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Damage);
	ECHOESOFTHEROZLOM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Heal);

	ECHOESOFTHEROZLOM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_GodMode);
	ECHOESOFTHEROZLOM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_UnlimitedHealth);

	ECHOESOFTHEROZLOM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Crouching);
	ECHOESOFTHEROZLOM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_AutoRunning);
	ECHOESOFTHEROZLOM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death);
	ECHOESOFTHEROZLOM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dying);
	ECHOESOFTHEROZLOM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dead);

	// These are mappings from MovementMode enums to GameplayTags associated with those enums (below)
	ECHOESOFTHEROZLOM_API	extern const TMap<uint8, FGameplayTag> MovementModeTagMap;
	ECHOESOFTHEROZLOM_API	extern const TMap<uint8, FGameplayTag> CustomMovementModeTagMap;

	ECHOESOFTHEROZLOM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Walking);
	ECHOESOFTHEROZLOM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_NavWalking);
	ECHOESOFTHEROZLOM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Falling);
	ECHOESOFTHEROZLOM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Swimming);
	ECHOESOFTHEROZLOM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Flying);

	ECHOESOFTHEROZLOM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Custom);

	// ==== Anomalies / Resonance ===============================================
	ECHOESOFTHEROZLOM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anomaly_Type_Cloud);
	ECHOESOFTHEROZLOM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anomaly_Type_Energy);
	ECHOESOFTHEROZLOM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anomaly_Type_Gravity);
	ECHOESOFTHEROZLOM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anomaly_Type_Biochemical);

	ECHOESOFTHEROZLOM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Anomaly_Stabilized);

	ECHOESOFTHEROZLOM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Anomaly_Toxic);
	ECHOESOFTHEROZLOM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Block_HealFull);

	ECHOESOFTHEROZLOM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Resonance_Action_Stabilize);
	ECHOESOFTHEROZLOM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Resonance_Action_Channel);

	ECHOESOFTHEROZLOM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GC_Anomaly_Toxic_Inside);
};
